version: "3"
services:
  proxy:
    container_name: linglink-proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway # localhost 통신 host.docker.internal로 요청
    depends_on:
      - linglink-front
      - linglink-back

  linglink-front:
    container_name: linglink-front
    image: east8237/linglink-front:latest
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - host.docker.internal:host-gateway

  linglink-back:
    container_name: linglink-back
    image: gardenee/linglink-back:latest
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
