name: Front CI/CD with Docker

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 # git repository 소스를 github action 서버로 다운

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v2 # 멀티 플랫폼으로 빌드하기 위한 액션
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # docker build 환경 구성 [docker/build-push-action@v4에 Platforms 속성 추가]
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-prod
          push: true
          tags: east8237/linglink-front:latest

      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          # sudo docker-compose down: docker compose안의 서비스 컨테이너 종료 및 삭제
          # sudo docker system prune -a: 사용하지 않는 docker resource 제거(container, image, volume, network)
          script: |
            sudo docker-compose down 
            sudo docker system prune -a
            sudo docker-compose pull
            nohup sudo docker-compose up &
            